; This is the fundamental definition of a Claims-Set for both
; CBOR and JSON. It is just a set of label-value pairs each of
; which is a claim.
;
; In CBOR the labels can be integers or strings with a strong preference for integers.
; For JSON, the labels are always strings.
;
; The values can be anything, with some consideration for types
; that can work in both CBOR and JSON

Claims-Set = {
    * $$claims-set-claims,
    * Claim-Label .feature "extended-label" => any
}

Claim-Label = int / text
