; The same as the standard time, but floating point
; is not allowed. 
time-int = #6.1(int)


; binary data that works for both JSON and CBOR. 
binary-data = JC< base64-url-text, bstr>

base64-url-text = tstr .regexp "[A-Za-z0-9_-]+"


; OID for both JSON and CBOR
general-oid = JC< json-oid, ~oid >

; This is a normative definition for the encoding of an OID
; as a text string in JSON as used by EAT
json-oid = tstr .regexp "([0-2])((\.0)|(\.[1-9][0-9]*))*"


; URI for both JSON and CBOR
general-uri = JC< text, ~uri >


; CoAP Content-Format from RFC 7252 section 12.3
coap-content-format = uint .le 65535

