; Top-level definition of a detached EAT bundle (DEAT) for CBOR and JSON

DEAT-Messages = DEAT-Tagged-Message / DEAT-Untagged-Message

; Note that tag number 602 is not yet assigned by IANA
; Also, 602 is replaced with "<TBD>" for the document by a
; sed substituion performed in the document Makefile
DEAT-Tagged-Message   = #6.602(DEAT-Untagged-Message)
DEAT-Untagged-Message = Detached-EAT-Bundle

Detached-EAT-Bundle = [
    main-token : Nested-Token,
    detached-claims-sets: {
        + tstr => JC<json-wrapped-claims-set,
                     cbor-wrapped-claims-set>
    }
]


; text content is a base64url encoded JSON-format Claims-Set

json-wrapped-claims-set = base64-url-text


cbor-wrapped-claims-set = bstr .cbor Claims-Set

