debug-disable-type = &(
    not-disabled: 0,
    disabled: 1,
    disabled-since-boot: 2,
    permanent-disable: 3,
    full-permanent-disable: 4
)

debug-disable-claim = (
    debug-disable => debug-disable-type
)
