; These are not yet assigned in any way and may change.
; These are intentionally above 24 so as to not use up
; single-byte labels.

; This file is used for cddl validation. It is not included
; in the document. The file eat-tbd-labels.cddl is for the document.

uptime = 31
chip-version = 32
board-version = 33
device-version = 34
intended-use = 41
sueids = 42
manifests = 43
swevidence = 44   
dloas = 45   

