; These are not yet assigned in any way and may change.

uptime-label = <TBD267>
boot-seed-label = <TB268>
intended-use-label = <TBD269>
dloas-label = <TBD270>
sw-name-label = <TBD271>
sw-version-label = <TBD272>
manifests-label = <TBD273>
swevidence-label = <TBD274>
swresults-label = <TBD275>



