; These are not yet assigned in any way and may change.
; These are intentionally above 24 so as to not use up
; single-byte labels.

uptime = <TBD31>
chip-version = <TBD32>
board-version = <TBD33>
device-version = <TBD34>
intended-use = <TBD41>
sueids = <TBD42>
manifests = <TBD43>
swevidence = <TBD44>
dloas = <TBD45>
