; The are temp
uptime = 19
chip-version = 21
board-version = 22
device-version = 23
chip-version-scheme = 24
board-version-scheme = 25
device-version-scheme = 26
ean-chip-version = 27
ean-board-version = 28
ean-device-version = 29
