; These are not yet assigned in any way and may change.
; These are intentionally above 24 so as to not use up
; single-byte labels.

; This file is used for cddl validation. It is not included
; in the document. The file eat-tbd-labels.cddl is for the document.

origination = 30
uptime = 31
chip-version = 32
board-version = 33
device-version = 34
chip-version-scheme = 35
board-version-scheme = 36
device-version-scheme = 37
ean-chip-version = 38
ean-board-version = 39
ean-device-version = 40
intended-use = 41
is-trusted = 42
verification-key = 43

