eat-claims = { ; the top-level payload that is signed using COSE or JOSE
    ? ueid-claim,
    ? nonce-claim,
    ? origination-claim,
    ? oemid-claim,
    ? hardware-version-claims,
    ? security-level-claim,
    ? secure-boot-claim,
    ? debug-disable-claim,
    ? location-claim,
    ? uptime-claim,
    ? submods-part,
    * $$eat-extension,
}

eat-token = EAT_Tagged ; This is a set of eat-claims signed using COSE

EAT_Tagged = #6.61(COSE_Sign1_Tagged) ; CWT tag

COSE_Sign1_Tagged = #6.18(bstr) ; COSE_Sign1

nonce = 10
ueid = 11
origination = 12
oemid = 13
security-level = 14
secure-boot = 15
debug-disable = 16
location = 17
uptime = 19
submods = 20

chip-version = 21
board-version = 22
device-version = 23
chip-version-scheme = 24
board-version-scheme = 25
device-version-scheme = 26
ean-chip-version = 27
ean-board-version = 28
ean-device-version = 29
