$$Claims-Set-Claims //= (
    intended-use-label =>
        JC<intended-use-json-type, intended-use-cbor-type>
)

intended-use-cbor-type = &(
    generic: 1,
    registration: 2,
    provisioning: 3,
    csr: 4,
    pop: 5
)

intended-use-json-type = 
    "generic" /
    "registration" /
    "provisioning" /
    "csr" /
    "pop" 
