ueid /= "ueid"
nonce /= "nonce"
origination /= "origination"
oemid /= "oemid"
security-level /= "security-level"
secure-boot /= "secure-boot"
debug-disble /= "debug-disable"
location /= "location"
age /= "age"
uptime /= "uptime"
nested-eat /= "nested-eat"
submods /= "submods"
timestamp /= "timestamp"

latitude /= "lat"
longitude /= "long"
altitude /= "alt"
accuracy /= "accry"
altitude-accuracy /= "alt-accry"
heading /= "heading"
speed /= "speed"
