; A JWT message is either a JWS or JWE in compact serialization form
; with the payload a Claims-Set. Compact serialization is the
; protected headers, payload and signature, each b64url encoded and
; separated by a ".". This CDDL simply matches top-level syntax of of
; a JWS or JWE since it is not possible to do more in CDDL.

JWT-Message = text .regexp [A-Za-z0-9_=-]+\.[A-Za-z0-9_=-]+\.[A-Za-z0-9_=-]+


; This defines the JSON equivalent of a UCCS message, an token
; with no integrity or authenticity protection.

UJCS-Message = Claims-Set


; This is the format of a DEB (Detached EAT Bundle) in JSON It
; contains one token that can be either CBOR or JSON format. It
; contains one or more Claims-Sets that must be JSON format. Each
; Claims-Set is base64 URL encoded because it is input to a MAC or
; signing algorithm.

;DEB-JSON-Message = [
;    main-token : Nested-Token,
;    detached-submodules: {
;        + tstr => tstr .regexp [A-Za-z0-9_=-] ; text content is a base64url
;	                                      ; encoded JSON-format Claims-Set
;]
