$$Claims-Set-Claims //= (
    manifests-label => manifests-type
)

manifests-type = [+ manifest-format]

manifest-format = [
    content-type:   coap-content-format,
    content-format: JC< $manifest-body-json,
                        $manifest-body-cbor >
]

; Because manifests are always text or byte strings, the "type socket"
; ($) is used rather than the "group socket ($$)".


; The JSON and CBOR types for CoSWID. CoSWIDs are of course always in
; CBOR format. When a CoSWID occurs in a CBOR token, it is bstr
; wrapped.  When a CoSWID occurs in a JSON token it is an
; untagged-coswid encoded in CBOR as usual, but then wrapped with B64
; encoding.

$manifest-body-cbor /= bytes .cbor untagged-coswid
$manifest-body-json /= base64-url-text

