$$Claims-Set-Claims //= (
    measurements-label => measurements-type
)

measurements-type = [+ measurements-format]

measurements-format = [
    content-type:   coap-content-format,
    content-format: JC< $$measurements-body-json,
                        $$measurements-body-cbor > 
]

; The JSON and CBOR types for CoSWID. CoSWIDs are of course alwas in
; CBOR format. When a CoSWID occurs in a CBOR token, it is bstr
; wrapped.  When a CoSWID occurs in a JSON token it is an
; untagged-coswid encoded in CBOR as usual, but then wrapped with B64
; encoding.
;
$$measurements-body-cbor /= bytes .cbor untagged-coswid
$$measurements-body-json /= base64-url-text


