; This is an EAT token that is nested inside a CBOR token.  When this
; occurs some means is needed to identify the type of token (signed,
; unsigned or detached EAT bundle) and the encoding format (JSON or CBOR). This is the
; only place in EAT where JSON can appear in a CBOR token.
;
; The nested token may be one of these:
;- A CWT format token
;- A CBOR-format detached EAT bundle
;- A JWT format token
;- A JWT-encoded detached EAT bundle
;- Some future-defined token type or encoding
;  such as a UCCS or UJCS


; The main EAT CDDL references Nested-Token.  When this file is
; included it is redirected to this. The JC < > generic doesn't work
; here.
Nested-Token = CBOR-Nested-Token

CBOR-Nested-Token =
    JSON-Token-Inside-CBOR-Token /
    CBOR-Token-Inside-CBOR-Token

; The CBOR tag mechanism is used to select between the various types
; of CBOR encoded tokens.
CBOR-Token-Inside-CBOR-Token = bstr .cbor $$EAT-CBOR-Tagged-Token

; The contents of this text string MUST be a JSON-encoded
; JSON-Nested-Token.  See the definition of JSON-Nested-Token.
JSON-Token-Inside-CBOR-Token = tstr 
