; This is an EAT token that is nested inside a CBOR token.  When this
; occurs some means is needed to identify the type of token (signed,
; unsigned or detached EAT bundle) and the encoding format (JSON or
; CBOR). This is the only place in EAT where JSON can appear in a CBOR
; token.
;
; The nested token may be one of these:
;- A CWT format token
;- A CBOR-format detached EAT bundle
;- A JWT format token
;- A JWT-encoded detached EAT bundle
;- Some future-defined token type or encoding
;  such as a UCCS or UJCS


CBOR-Nested-Token =
    JSON-Token-Inside-CBOR-Token /
    CBOR-Token-Inside-CBOR-Token

; The CBOR tag mechanism is used to select between the various types
; of CBOR encoded tokens.
CBOR-Token-Inside-CBOR-Token = bstr .cbor $EAT-CBOR-Tagged-Token

; The contents of this text string MUST be a JSON-encoded
; JSON-Nested-Token.  See the definition of JSON-Nested-Token.
JSON-Token-Inside-CBOR-Token = tstr 

$JSON-Nested-Token-Type = "JWT" / "CBOR" / "BUNDLE"
$JSON-Nested-Token-Value = JWT-Message /
                  CBOR-Token-Inside-JSON-Token / Detached-EAT-Bundle

JSON-Nested-Token = [
   type : $JSON-Nested-Token-Type,
   nested-token : $JSON-Nested-Token-Value
]
