$$Claims-Set-Claims //= (
    security-level-label => 
        JC<security-level-json-type, 
        security-level-cbor-type>
)

security-level-cbor-type = &(
    unrestricted: 1,
    restricted: 2,
    secure-restricted: 3,
    hardware: 4
)

security-level-json-type = 
    "unrestricted" /
    "restricted" /
    "secure-restricted" /
    "hardware"
