; This is the part of a token that contains all the submodules.  It
; is a peer with the claims in the token, but not a claim, only a
; map/object to hold all the submodules.
;
$$Claims-Set-Claims //= (submods-label => { + text => Submodule })


; A submodule can be:
; - A simple Claims-Set (always encoded same as the enclosing token)
; - A nested token which is a fully formed EAT token or any type.
;   It may be CBOR or JSON encoded, or signed or unsigned.
;   See the definition of Nested-Token in cbor-nested-tokend.cddl
;   or in json-nested-token.cddl.
; - The digest of a detached Claims-Set (encoded the same as
;   the enclosing token)
;
Submodule = Claims-Set / Nested-Token / Detached-Submodule-Digest
